#port setting
server:
  port: 9000
  
#jsp setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp  
      
#mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bitcamp?serverTimezone=Asia/Seoul
    username: root
    password: qwer1234
    
#mybatis setting
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml        
  